# Generated by Django 6.0.3 on 2026-06-16 18:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_company_fiscal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('sucursal', 'Sucursal'), ('deposito', 'Depósito'), ('transito', 'En Tránsito'), ('virtual', 'Virtual')], default='principal', max_length=20, verbose_name='Tipo')),
                ('direccion', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacen',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(default='unidad', max_length=20, verbose_name='Unidad de medida')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Precio costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Precio venta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('referencia', models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario.almacen', verbose_name='Almacén destino')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.almacen', verbose_name='Almacén origen')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.articulo', verbose_name='Artículo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'movimiento_stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Cantidad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.almacen', verbose_name='Almacén')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.articulo', verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
                'ordering': ['articulo__codigo'],
                'unique_together': {('almacen', 'articulo')},
            },
        ),
    ]
