# Generated by Django 6.0.3 on 2026-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='stock_cantidad_no_negativa'),
        ),
    ]
