# Generated by Django 6.0.6 on 2026-06-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_empresaidioma'),
        ('inventario', '0002_stock_stock_cantidad_no_negativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloTraduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción traducida')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='inventario.articulo', verbose_name='Artículo')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo_traducciones', to='erp_core.idioma', verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Traducción de Artículo',
                'verbose_name_plural': 'Traducciones de Artículos',
                'db_table': 'articulo_traduccion',
                'ordering': ['articulo__codigo', 'idioma__codigo'],
                'unique_together': {('articulo', 'idioma')},
            },
        ),
    ]
