# Generated by Django 6.0.6 on 2026-06-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_articulotraduccion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='stock_cantidad_no_negativa',
        ),
    ]
