# Generated by Django 6.0.3 on 2026-06-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_company_fiscal_fields'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'db_table': 'idioma',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('cuit', models.CharField(blank=True, default='', max_length=20, verbose_name='CUIT')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('contacto_crm', models.ForeignKey(blank=True, help_text='Vínculo opcional con contacto del CRM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_erp', to='crm.contact', verbose_name='Contacto CRM')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['razon_social'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, help_text='Vínculo opcional con usuario del sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor_erp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedor',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
