# Generated by Django 6.0.3 on 2026-06-16 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_stock_stock_cantidad_no_negativa'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén desde el cual se descontará el stock al confirmar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='inventario.almacen', verbose_name='Almacén'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
