# Generated by Django 6.0.6 on 2026-06-17 14:52
#
# NOTE: Esta migración consolida el drift histórico entre los nombres de
# índices presentes en la base de datos (prefijo "adora_*" y "apice_*",
# heredados de iteraciones anteriores del proyecto) y los nombres que
# Django 6.0.6 espera ahora. Se usa SQL idempotente (ALTER INDEX IF EXISTS)
# para que la migración funcione independientemente del estado actual de
# la BD, y SeparateDatabaseAndState para mantener sincronizado el state
# del ORM con la BD final.

from django.db import migrations, models


def _rename_index_sql(candidates, new_name):
    """
    Genera SQL que renombra el primer índice existente entre `candidates`
    al `new_name`. Si ya existe `new_name`, no hace nada (idempotente).
    """
    parts = [
        "DO $$",
        "BEGIN",
        f"  IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = '{new_name}') THEN",
        "    RETURN;",
        "  END IF;",
    ]
    for old in candidates:
        parts.append(
            f"  IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = '{old}') THEN"
        )
        parts.append(
            f"    EXECUTE 'ALTER INDEX {old} RENAME TO {new_name}';"
        )
        parts.append("    RETURN;")
        parts.append("  END IF;")
    parts.append("END$$;")
    return "\n".join(parts)


class Migration(migrations.Migration):

    dependencies = [
        ('apice', '0012_mercadolibrecategory'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=_rename_index_sql(
                        ['adora_email_integra_a6639a_idx',
                         'apice_email_integra_a6639a_idx'],
                        'crm_emailme_integra_6cf08a_idx',
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_rename_index_sql(
                        ['adora_email_message_9dfb93_idx',
                         'apice_email_message_9dfb93_idx'],
                        'crm_emailme_message_8a0f88_idx',
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_rename_index_sql(
                        ['mercadolibr_ml_pare_a1b2c3_idx'],
                        'mercadolibr_ml_pare_348d5c_idx',
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='emailmessage',
                    new_name='crm_emailme_integra_6cf08a_idx',
                    old_name='apice_email_integra_a6639a_idx',
                ),
                migrations.RenameIndex(
                    model_name='emailmessage',
                    new_name='crm_emailme_message_8a0f88_idx',
                    old_name='apice_email_message_9dfb93_idx',
                ),
                migrations.RenameIndex(
                    model_name='mercadolibrecategory',
                    new_name='mercadolibr_ml_pare_348d5c_idx',
                    old_name='mercadolibr_ml_pare_a1b2c3_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='mercadolibrereplytemplate',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords que activan auto-reply. Vacío = solo respuesta manual.'),
        ),
        migrations.AlterField(
            model_name='mercadolibrereplytemplate',
            name='response_text',
            field=models.TextField(help_text='Texto de la respuesta'),
        ),
    ]
