# Generated by Django 4.2.1 on 2026-03-09 21:12

from django.db import migrations, models
import uuid


def generate_api_keys(apps, schema_editor):
    """Generar API Keys únicas para todas las empresas existentes"""
    Company = apps.get_model('accounts', 'Company')
    for company in Company.objects.all():
        company.api_key = uuid.uuid4().hex
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Primero agregar el campo sin unique constraint
        migrations.AddField(
            model_name='company',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        # Generar API Keys para empresas existentes
        migrations.RunPython(generate_api_keys, migrations.RunPython.noop),
        # Ahora agregar la constraint unique
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
