# Generated by Django 6.0.3 on 2026-03-12 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('metalurgica', 'Metalúrgica'), ('construccion', 'Construcción'), ('educacion', 'Educación'), ('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('comercio', 'Comercio'), ('servicios', 'Servicios'), ('manufactura', 'Manufactura'), ('agricultura', 'Agricultura'), ('transporte', 'Transporte'), ('inmobiliaria', 'Inmobiliaria'), ('gastronomia', 'Gastronomía'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Industria'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar usuarios'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_emails',
            field=models.BooleanField(default=True, verbose_name='Puede enviar emails'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_contacts',
            field=models.BooleanField(default=True, verbose_name='Puede ver contactos'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_deals',
            field=models.BooleanField(default=True, verbose_name='Puede ver deals'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_integrations',
            field=models.BooleanField(default=True, verbose_name='Puede ver integraciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_pipeline',
            field=models.BooleanField(default=True, verbose_name='Puede ver pipeline'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_settings',
            field=models.BooleanField(default=False, verbose_name='Puede ver configuración'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Administrador de la empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actividad'),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('security', 'Problema de Seguridad'), ('improvement', 'Mejora'), ('integration', 'Integración'), ('other', 'Otro')], max_length=20)),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Respuesta del Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
