# Generated by Django 6.0.3 on 2026-03-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_description_company_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('message', models.TextField(verbose_name='¿Qué te interesaría encontrar en Apice?')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('account_created', 'Cuenta Creada'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Notas del Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Demo',
                'verbose_name_plural': 'Solicitudes de Demo',
                'ordering': ['-created_at'],
            },
        ),
    ]
