# Generated by Django 6.0.6 on 2026-06-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_fiscal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código corto único de la empresa (ERP).', max_length=10, null=True, unique=True, verbose_name='Código de empresa'),
        ),
    ]
