# Generated by Django 6.0.6 on 2026-06-23 14:04

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.ERPUserManager()),
            ],
        ),
    ]
