# Generated by Django 6.0.3 on 2026-03-19 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systemnotification_usernotification'),
        ('crm', '0006_mercadolibreoauthstate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLibreAutoReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre identificador de la plantilla', max_length=200)),
                ('keywords', models.JSONField(default=list, help_text='Lista de palabras clave que activan esta respuesta')),
                ('response_text', models.TextField(help_text='Texto de la respuesta automática')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Mayor prioridad se evalúa primero (0 = normal)')),
                ('times_used', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Respuesta Automática',
                'verbose_name_plural': 'Plantillas de Respuesta Automática',
                'db_table': 'mercadolibre_auto_reply_templates',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mercadolibrequestion',
            name='auto_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mercadolibreautoreplytemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_auto_reply_templates', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='mercadolibreautoreplytemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_auto_reply_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mercadolibrequestion',
            name='auto_reply_template',
            field=models.ForeignKey(blank=True, help_text='Template usado para la respuesta automática', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_answered', to='crm.mercadolibreautoreplytemplate'),
        ),
    ]
