# Generated by Django 6.0.3 on 2026-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_reply_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibreproduct',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mercadolibreproduct',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mercadolibreproduct',
            name='listing_type_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mercadolibreproduct',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=30),
        ),
    ]
