# Generated by Django 6.0.6 on 2026-06-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_codigo'),
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Idioma por defecto de la empresa.', verbose_name='Predeterminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='accounts.company', verbose_name='Empresa')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='erp_core.idioma', verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Idioma de Empresa',
                'verbose_name_plural': 'Idiomas de Empresas',
                'db_table': 'empresa_idioma',
                'ordering': ['empresa', 'idioma'],
                'unique_together': {('empresa', 'idioma')},
            },
        ),
    ]
